# Generated by Django 2.2.3 on 2019-07-03 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseQueries', '0002_auto_20190703_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='movierating',
            name='rating_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
